version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn %%main_app_name%%.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - %%cleaned_project_slug%%_staticfiles:/home/%%project_container_root_folder%%/staticfiles
      - %%cleaned_project_slug%%_mediafiles:/home/%%project_container_root_folder%%/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - %%cleaned_project_slug%%_pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - %%cleaned_project_slug%%_staticfiles:/home/%%project_container_root_folder%%/staticfiles
      - %%cleaned_project_slug%%_mediafiles:/home/%%project_container_root_folder%%/mediafiles
      - %%cleaned_project_slug%%_certs:/etc/nginx/certs
      - %%cleaned_project_slug%%_html:/usr/share/nginx/html
      - %%cleaned_project_slug%%_vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - %%cleaned_project_slug%%_certs:/etc/nginx/certs
      - %%cleaned_project_slug%%_html:/usr/share/nginx/html
      - %%cleaned_project_slug%%_vhost:/etc/nginx/vhost.d
      - %%cleaned_project_slug%%_acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  %%cleaned_project_slug%%_pg_data:
  %%cleaned_project_slug%%_staticfiles:
  %%cleaned_project_slug%%_mediafiles:
  %%cleaned_project_slug%%_certs:
  %%cleaned_project_slug%%_html:
  %%cleaned_project_slug%%_vhost:
  %%cleaned_project_slug%%_acme: